# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'MBProgressHUD'
target 'Xing_iOS_Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Xing_iOS_Test

  target 'Xing_iOS_TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
